package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/sirolad/MagicStreamMovies/Server/MagicStreamMovies/Server/internal/config"
	"github.com/sirolad/MagicStreamMovies/Server/MagicStreamMovies/Server/internal/handler"
	"github.com/sirolad/MagicStreamMovies/Server/MagicStreamMovies/Server/internal/middleware"
	"github.com/sirolad/MagicStreamMovies/Server/MagicStreamMovies/Server/internal/repository"
	"github.com/sirolad/MagicStreamMovies/Server/MagicStreamMovies/Server/internal/service"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"

	_ "github.com/sirolad/MagicStreamMovies/Server/MagicStreamMovies/Server/docs" // docs is generated by Swag CLI, you have to import it.
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           MagicStreamMovies API
// @version         1.0
// @description     This is the API server for MagicStreamMovies application.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Enter your Bearer token (e.g., "eyJhbGci..."). The "Bearer " prefix is optional.

func main() {
	// 1. Config
	cfg := config.LoadConfig()

	// 2. Database
	fmt.Println("Connecting to MongoDB at:", cfg.MongoURI)
	clientOptions := options.Client().ApplyURI(cfg.MongoURI)
	client, err := mongo.Connect(clientOptions)
	if err != nil {
		log.Fatal(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := client.Ping(ctx, nil); err != nil {
		log.Fatal(err)
	}
	defer func() {
		if err := client.Disconnect(context.Background()); err != nil {
			log.Println(err)
		}
	}()

	db := client.Database(cfg.DatabaseName)

	// 3. Repositories
	userRepo := repository.NewUserRepository(db)
	movieRepo := repository.NewMovieRepository(db)

	// 4. Services
	userService := service.NewUserService(userRepo, cfg)
	movieService := service.NewMovieService(movieRepo, userRepo, cfg)

	// 5. Handlers
	userHandler := handler.NewUserHandler(userService)
	movieHandler := handler.NewMovieHandler(movieService)

	// 6. Router
	router := gin.Default()

	// CORS
	corsConfig := cors.Config{
		AllowOrigins:     cfg.AllowedOrigins,
		AllowMethods:     []string{"GET", "POST", "PATCH", "DELETE", "PUT", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}
	router.Use(cors.New(corsConfig))

	// Routes
	router.Any("/", func(c *gin.Context) {
		if c.Request.Method == "OPTIONS" {
			c.Status(204)
			return
		}
		c.JSON(200, gin.H{"status": "ok", "message": "MagicStreamMovies API Running"})
	})

	router.GET("/hello", func(c *gin.Context) {
		c.String(200, "Hello, MagicStreamMovies!")
	})

	// Swagger Route
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Unprotected
	router.POST("/register", userHandler.RegisterUser)
	router.POST("/login", userHandler.LoginUser)
	router.POST("/user/logout", userHandler.LogoutHandler)
	router.GET("/genres", movieHandler.GetAllGenres)
	router.GET("/movies", movieHandler.GetMovies)

	// Protected
	protected := router.Group("/")
	protected.Use(middleware.NewAuthMiddleware(cfg))
	{
		protected.GET("/movie/:imdb_id", movieHandler.GetMovie)
		protected.POST("/movie", movieHandler.AddMovie)
		protected.GET("/recommendedMovies", movieHandler.GetRecommendedMovies)

		// Additional routes that existed in controllers but weren't wired
		protected.PATCH("/movie/:imdb_id/review", movieHandler.UpdateAdminReview)
		protected.POST("/user/refresh-token", userHandler.RefreshTokenHandler)
	}

	if err := router.Run(":8080"); err != nil {
		fmt.Println("Failed to start server: ", err)
	}
}
